apiVersion: batch/v1
kind: CronJob
metadata:
  name: demo-cronjob
  namespace: my-app    
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-container
            image: busybox:latest
            command: ["sh", "-c", "echo Hello World"]
          restartPolicy: OnFailure
